#!/usr/bin/env bash

# Install nginx
sudo apt-get -y update
sudo apt-get -y install nginx

# Configure nginx to listen on port 80 and serve "Hello World!" at the root
echo "Hello World!" | sudo tee/var/www/html/index.html

# Restart nginx
sudo service nginx start
